
remote.connectionprovider.create.options.org.xnio.Options.SSL_ENABLED=false
remote.connections=default
remote.connection.default.host=localhost
remote.connection.default.port = 4447
remote.connection.default.connect.options.org.xnio.Options.SASL_POLICY_NOANONYMOUS=false

# The settings below are only used when connecting a remote EJB client to an EJBCA cluster
# in HA mode.  If these are not present, the client will round-robbin commands
# to all nodes in the cluster, and will receive CliAuthenticationToken authentication
# errors
deployment.node.selector=org.ejbca.ui.cli.SameDeploymentNodeSelector
# `ejb` is the default cluster name. If your cluster is named differently, change
# these two lines
remote.clusters=ejb
remote.cluster.ejb.clusternode.selector=org.ejbca.ui.cli.SameClusterNodeSelector