package org.ejbca.core.ejb.log;

import java.util.ArrayList;
import java.util.Date;

import javax.naming.Context;

import junit.framework.TestCase;

import org.ejbca.core.model.log.Admin;
import org.ejbca.core.model.log.LogConstants;

public class LoggingStressTest extends TestCase {
	
	private static final int NUMBER_OF_THREADS = 10; 
	private static final int TIME_TO_RUN = 1000 * 60 * 60 * 24 * 7; // Run for a week 
	private ILogSessionHome logSessionHome = null;

    protected void setUp() throws Exception {
        Context ctx = new javax.naming.InitialContext();
		logSessionHome = (ILogSessionHome) javax.rmi.PortableRemoteObject.narrow(ctx.lookup("LogSession"), ILogSessionHome.class );            
    }

    protected void tearDown() throws Exception {
    }

    public void test01LogALot() throws Exception {
		ArrayList<Thread> threads = new ArrayList<Thread>();
		for (int i=0; i<NUMBER_OF_THREADS; i++) {
	        Thread thread = new Thread(new LogTester(i, TIME_TO_RUN), "LogTester-"+i);
	        thread.start();
	        System.out.println("Started LogTester-"+i);
	        threads.add(thread);
		}
		for (Thread thread : threads) {
			thread.join();
		}
    }
    
    private class LogTester implements Runnable {
    	
    	private long runTime = 0;
    	private long startTime = 0;
    	private int threadId = 0;
    	
    	public LogTester(String name) {}
    	
    	LogTester(int threadId, long runTime) {
    		this.threadId = threadId;
    		this.startTime = new Date().getTime();
    		this.runTime = runTime;
    	}
    	
    	private ILogSessionRemote logSession = null;          
    	Admin internalAdmin = new Admin(Admin.TYPE_INTERNALUSER);
    	public void run() {
            try {
            	logSession = logSessionHome.create();
            	int i = 0;
            	long delta = 0;
            	while ((delta =System.currentTimeMillis() - startTime) < runTime) {
                	logSession.log(internalAdmin, 0, 0, new Date(), null, null, LogConstants.EVENT_INFO_UNKNOWN, "This LogEvent was generated by the log stress test.");
                	i++;
                	if (((delta * 100) / runTime) % 10 == 0) {
                		System.out.println(threadId+" has logged "+i+" events.");
                		System.out.flush();
                	}
                	Thread.yield();
            	}
                System.out.println("\nThread "+threadId+" finished in "+((delta)/1000) + "."+((delta)%1000)+" seconds.");
                System.out.println("Throughput: "+(i/(delta/1000)) + "." + (i%(delta/1000)) + " log-invocations/second.");
			} catch (Exception e) {
				e.printStackTrace();
            	assertTrue(false);
			}    		
    	}
    }
}
