/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.publisher;

/**
 * Local home interface for PublisherData.
 */
public interface PublisherDataLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PublisherDataLocal";
   public static final String JNDI_NAME="PublisherDataLocal";

   public se.anatom.ejbca.ca.publisher.PublisherDataLocal create(java.lang.Integer id , java.lang.String name , se.anatom.ejbca.ca.publisher.BasePublisher publisher)
      throws javax.ejb.CreateException;

   public se.anatom.ejbca.ca.publisher.PublisherDataLocal findByName(java.lang.String name)
      throws javax.ejb.FinderException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public se.anatom.ejbca.ca.publisher.PublisherDataLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
