/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.publisher;

/**
 * Local interface for PublisherData.
 */
public interface PublisherDataLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Integer getId(  ) ;

   public java.lang.String getName(  ) ;

   public void setName( java.lang.String name ) ;

   public int getUpdateCounter(  ) ;

   /**
    * Method that returns the publisher data and updates it if nessesary.
    */
   public se.anatom.ejbca.ca.publisher.BasePublisher getPublisher(  ) ;

   /**
    * Method that saves the publisher data to database.
    */
   public void setPublisher( se.anatom.ejbca.ca.publisher.BasePublisher publisher ) ;

}
