/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ra.raadmin;

/**
 * Local interface for EndEntityProfileData.
 */
public interface EndEntityProfileDataLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Integer getId(  ) ;

   public java.lang.String getProfileName(  ) ;

   public void setProfileName( java.lang.String profilename ) ;

   /**
    * Method that returns the end entity profiles and updates it if nessesary.
    * @return DOCUMENT ME!
    */
   public se.anatom.ejbca.ra.raadmin.EndEntityProfile getProfile(  ) ;

   /**
    * Method that saves the admin preference to database.
    * @param profile DOCUMENT ME!
    */
   public void setProfile( se.anatom.ejbca.ra.raadmin.EndEntityProfile profile ) ;

}
