/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ra.raadmin;

/**
 * Local interface for GlobalConfigurationData.
 */
public interface GlobalConfigurationDataLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getConfigurationId(  ) ;

   public void setConfigurationId( java.lang.String id ) ;

   /**
    * Method that returns the globalconfigurtation and updates it if nessesary.
    */
   public se.anatom.ejbca.ra.raadmin.GlobalConfiguration getGlobalConfiguration(  ) ;

   /**
    * Method that saves the global configuration to database.
    */
   public void setGlobalConfiguration( se.anatom.ejbca.ra.raadmin.GlobalConfiguration globalconfiguration ) ;

}
