/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ra.raadmin;

/**
 * Local home interface for GlobalConfigurationData.
 */
public interface GlobalConfigurationDataLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GlobalConfigurationDataLocal";
   public static final String JNDI_NAME="GlobalConfigurationDataLocal";

   public se.anatom.ejbca.ra.raadmin.GlobalConfigurationDataLocal create(java.lang.String configurationId , se.anatom.ejbca.ra.raadmin.GlobalConfiguration globalConfiguration)
      throws javax.ejb.CreateException;

   public se.anatom.ejbca.ra.raadmin.GlobalConfigurationDataLocal findByConfigurationId(java.lang.String id)
      throws javax.ejb.FinderException;

   public se.anatom.ejbca.ra.raadmin.GlobalConfigurationDataLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
