pipeline {
	agent {
		label "docker"
	}
    
    stages {
		stage('cleanup') {
            steps {
                sh "docker container rm ee_al35_openjdk8_unit -f || true"
                sh "rm -rf ear"
            }
        }
        stage('variables') {
            steps {
                script{        
                    LOCAL_BUILD_PATH = "$env.WORKSPACE"
                }
            }
        }
        stage('run unit tests') {
            steps {
                sh "mkdir ear"
                dir ('ejbca/jenkins-files/EE_AL35_OpenJDK8_UNIT') {
                    echo LOCAL_BUILD_PATH
                    sh "docker build -t ee_al35_openjdk8_unit ."
                    sh 'docker run --name ee_al35_openjdk8_unit -v \"${LOCAL_BUILD_PATH}\":/app ee_al35_openjdk8_unit'
                }
            }
        }
    }
    post {
        always {
            junit "ejbca/**/reports/**/TEST-*.xml"
        }
    }
}
