pipeline {
	agent {
		label "docker"
	}
    
    stages {
        stage('run unit tests') {
            agent {
                // build and run (later also cleanup) the Docker container
                dockerfile {
                    reuseNode true
                    dir 'ejbca/jenkins-files/EE_AL35_OpenJDK8_UNIT'
                    filename 'Dockerfile'
                    additionalBuildArgs  '--disable-content-trust=false --pull'
                    args '--group-add root'
                }
            }
            environment {
                ANT_OPTS = "-XX:+UseG1GC -XX:+UseCompressedOops -XX:OnOutOfMemoryError='kill -9 %p' -Xms64m -Xmx1024m"
                TEST_OPTS = "-XX:+UseG1GC -XX:+UseCompressedOops -XX:OnOutOfMemoryError='kill -9 %p' -Xms64m -Xmx256m"
            }
            steps {
                // Run these steps inside the running docker container
                dir ('ejbca') {
                    sh "cp /opt/conf/* conf/"
                    sh "ant -q -Dappserver.home=/tmp -Dappserver.type=jboss -Dejbca.productionmode=false clean build test:runsa -Dtests.jvmargs=\"\$TEST_OPTS\""
                }
                // gather the results
                junit "ejbca/**/reports/**/TEST-*.xml"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
