--
-- These definitions should work for EJBCA 3.6.x, PostgreSQL 8.1 or 8.2.
--

DROP TABLE ACCESSRULESDATA;

DROP TABLE ADMINENTITYDATA;
     
DROP TABLE ADMINGROUPDATA;

DROP TABLE ADMINPREFERENCESDATA;

DROP TABLE APPROVALDATA;

DROP TABLE AUTHORIZATIONTREEUPDATEDATA;

DROP TABLE CADATA;

DROP TABLE CERTIFICATEDATA;

DROP TABLE CERTIFICATEPROFILEDATA;

DROP TABLE CERTREQHISTORYDATA;

DROP TABLE CRLDATA;

DROP TABLE ENDENTITYPROFILEDATA;

DROP TABLE GLOBALCONFIGURATIONDATA;

DROP TABLE HARDTOKENCERTIFICATEMAP;
     
DROP TABLE HARDTOKENDATA;

DROP TABLE HARDTOKENISSUERDATA;

DROP TABLE HARDTOKENPROFILEDATA;

DROP TABLE HARDTOKENPROPERTYDATA;

DROP TABLE KEYRECOVERYDATA;

DROP TABLE LOGCONFIGURATIONDATA;

DROP TABLE LOGENTRYDATA;

DROP TABLE PROTECTEDLOGDATA;

DROP TABLE PROTECTEDLOGEXPORTDATA;

DROP TABLE PROTECTEDLOGTOKENDATA;

DROP TABLE PUBLISHERDATA;

DROP TABLE SERVICEDATA;

DROP TABLE TABLEPROTECTDATA;

DROP TABLE USERDATA;

DROP TABLE USERDATASOURCEDATA;
