/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.crl;

/**
 * Home interface for CreateCRLSession.
 */
public interface ICreateCRLSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CreateCRLSession";
   public static final String JNDI_NAME="CreateCRLSession";

   public se.anatom.ejbca.ca.crl.ICreateCRLSessionRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
