/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.crl;

/**
 * Remote interface for CreateCRLSession.
 */
public interface ICreateCRLSessionRemote
   extends javax.ejb.EJBObject
{
   /**
    * Generates a new CRL by looking in the database for revoked certificates and generating a CRL.
    * @param admin administrator performing the task
    * @param issuerdn ofof the ca
    * @throws EJBException om ett kommunikations eller systemfel intr?ffar.
    */
   public void run( se.anatom.ejbca.log.Admin admin,java.lang.String issuerdn )
      throws java.rmi.RemoteException;

   /**
    * Method that checks if there are any CRLs needed to be updated and then creates their CRLs. This method can be called by a scheduler or a service.
    * @param admin administrator performing the task
    * @return the number of crls created.
    * @throws EJBException om ett kommunikations eller systemfel intr?ffar.
    */
   public int createCRLs( se.anatom.ejbca.log.Admin admin )
      throws java.rmi.RemoteException;

}
