/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ra;

/**
 * Local home interface for UserAdminSession.
 */
public interface IUserAdminSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserAdminSessionLocal";
   public static final String JNDI_NAME="UserAdminSessionLocal";

   public se.anatom.ejbca.ra.IUserAdminSessionLocal create()
      throws javax.ejb.CreateException;

}
