/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ra;

/**
 * Primary key for UserData.
 */
public class UserDataPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String username;

   public UserDataPK()
   {
   }

   public UserDataPK( java.lang.String username )
   {
      this.username = username;
   }

   public java.lang.String getUsername()
   {
      return username;
   }

   public void setUsername(java.lang.String username)
   {
      this.username = username;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.username != null) _hashCode += this.username.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof se.anatom.ejbca.ra.UserDataPK) )
         return false;

      se.anatom.ejbca.ra.UserDataPK pk = (se.anatom.ejbca.ra.UserDataPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.username != null )
         {
            eq = eq && this.username.equals( pk.getUsername() );
         }
         else  // this.username == null
         {
            eq = eq && ( pk.getUsername() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.username).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
