pipeline {
	agent {
		label "docker"
	}
	environment {
		JENKINS_JOB_FOLDER = 'EE_COS7_OpenJDK8_WF10_NOHSM_MSSQL2017'
		DOCKER_NAME_BASE = 'ee_cos7_openjdk8_wf10_nohsm_mssql2017'
		DOCKER_NAME_NET = 'net_ee_cos7_openjdk8_wf10_nohsm_mssql2017'
		DOCKER_NAME_DB = 'db_ee_cos7_openjdk8_wf10_nohsm_mssql2017'
		DB_PORTS= '1433:1433'
		DB_PASSWORD = 'MyEjbcaPass1100'
	}
	stages {
		stage('verify that space is clean') {
			steps {
				sh "docker container rm ${env.DOCKER_NAME_DB} -f || true"
				sh "docker container rm ${env.DOCKER_NAME_BASE} -f || true"
				sh "docker network rm ${env.DOCKER_NAME_NET} || true"
				sh "rm -rf ear"
				sh "chmod -R a+rwX ${env.WORKSPACE}"
			}
		}
		stage('network') {
			steps {
				sh "docker network create --driver bridge ${env.DOCKER_NAME_NET} || true"
			}
		}
		stage('database') {
			steps {
			    dir ("ejbca/jenkins-files/${env.JENKINS_JOB_FOLDER}/mssql") {
			        sh "docker build -t ${env.DOCKER_NAME_DB} -m 3GB . "
			        sh "docker run -d --name ${env.DOCKER_NAME_DB} --net=${env.DOCKER_NAME_NET} -p ${env.DB_PORTS} -v ${env.WORKSPACE}:/app:z ${env.DOCKER_NAME_DB}"
			        sh "sleep 120"
			        sh "docker exec -i ${env.DOCKER_NAME_DB} /opt/mssql-tools/bin/sqlcmd -U sa -P '${env.DB_PASSWORD}' -Q 'CREATE DATABASE ejbca'"
			        sh "docker cp ${env.WORKSPACE}/ejbca/doc/sql-scripts/create-tables-ejbca-mssql.sql ${env.DOCKER_NAME_DB}:/app/"
			        sh "docker cp ${env.WORKSPACE}/ejbca/doc/sql-scripts/create-index-ejbca.sql ${env.DOCKER_NAME_DB}:/app/"
			        sh "docker exec -i ${env.DOCKER_NAME_DB} /opt/mssql-tools/bin/sqlcmd -U sa -P '${env.DB_PASSWORD}' -i '/app/create-tables-ejbca-mssql.sql'"
			        sh "docker exec -i ${env.DOCKER_NAME_DB} /opt/mssql-tools/bin/sqlcmd -U sa -P '${env.DB_PASSWORD}' -i '/app/create-index-ejbca.sql'"
			        sh "docker exec -i ${env.DOCKER_NAME_DB} /opt/mssql-tools/bin/sqlcmd -U sa -P '${env.DB_PASSWORD}' -Q 'CREATE INDEX userdata_idx_test1 ON UserData (cAId)'"
			    }
			}
		}
		stage('deploy and run system tests') {
			steps {
				sh "mkdir ear || true"
				dir ("ejbca/jenkins-files/${env.JENKINS_JOB_FOLDER}") {
					sh "docker build -t ${env.DOCKER_NAME_BASE} -m 3GB ."
					sh "docker run --name ${env.DOCKER_NAME_BASE} --net=${env.DOCKER_NAME_NET} -v ${env.WORKSPACE}:/app:z ${env.DOCKER_NAME_BASE}"
				}
			}
		}
		stage('save test results') {
			steps {
				junit "ejbca/**/reports/**/TEST-*.xml"
			}
		}
	}
	post {
		always {
			sh "docker stop --time=1 ${env.DOCKER_NAME_BASE} || true"
			sh "docker rm -f ${env.DOCKER_NAME_BASE} || true"
			sh "docker stop --time=1 ${env.DOCKER_NAME_DB} || true"
			sh "docker rm -f ${env.DOCKER_NAME_DB} || true"
			sh "docker network rm ${env.DOCKER_NAME_NET} || true"
			cleanWs()
		}
	}
}
