
package se.anatom.ejbca.ra.authorization;

/**
 * Created 2002-jun-27 16:11:07
 * Code generated by the Forte For Java EJB Workshop
 * @author tomselleck
 */

public final class AccessRulesPK implements java.io.Serializable {

    public int pK;


    public AccessRulesPK(java.lang.String usergroupname, java.lang.String resource) {
        this.pK =
        ((usergroupname==null?0:usergroupname.hashCode())
        ^
        (resource==null?0:resource.hashCode()));
    }

    public AccessRulesPK() {
    }

    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    public boolean equals(java.lang.Object otherOb) {
        if (!(otherOb instanceof se.anatom.ejbca.ra.authorization.AccessRulesPK)) {
            return false;
        }
        se.anatom.ejbca.ra.authorization.AccessRulesPK other = (se.anatom.ejbca.ra.authorization.AccessRulesPK) otherOb;
        return (pK==other.pK);
    }

    /**
     * @see java.lang.Object#hashCode()
     */
    public int hashCode() {
        return this.pK;
    }

}
