-- subjectAltName column size is increased in CertificateData, NoConflictCertificateData and UserData tables
-- ALTER TABLE UserData MODIFY subjectAltName VARCHAR(8000);
-- ALTER TABLE CertificateData MODIFY subjectAltName VARCHAR(8000);
-- ALTER TABLE NoConflictCertificateData MODIFY subjectAltName VARCHAR(8000);