pipeline {
	agent {
		label "docker"
	}
    stages {
		stage('cleanup') {
            steps {
                sh "docker container rm mariadb2 -f || true"
                sh "docker container rm ee_cos7_openjdk8_wf12_nohsm_mariadb -f || true"
                sh "rm -rf ear"
            }
        }
        stage('network') {
            steps {
                sh "docker network create --driver bridge my_isolated_bridge_network || true"
            }
        }
		stage('database') {
            steps {
                sh "docker run --name mariadb2 -e MYSQL_ROOT_PASSWORD=foo123 -e MYSQL_DATABASE=ejbca -e MYSQL_USER=ejbca -e MYSQL_PASSWORD=ejbca --net=my_isolated_bridge_network -d mariadb:10.2.17"
            }
        }
        stage('deploy and run system tests') {
            steps {
                sh "mkdir ear"
                dir ('ejbca/jenkins-files/EE_COS7_OpenJDK8_WF12_NOHSM_MariaDB') {
                    sh "docker build -t ee_cos7_openjdk8_wf12_nohsm_mariadb -m 2GB ."
                    sh "docker run --name ee_cos7_openjdk8_wf12_nohsm_mariadb --net=my_isolated_bridge_network -v /home/jenkins/workspace/EJBCA/EE_COS7_OpenJDK8_WF12_NOHSM_MariaDB:/app ee_cos7_openjdk8_wf12_nohsm_mariadb"
                }
            }
        }
    }
    post {
        always {
            junit "ejbca/**/reports/**/TEST-*.xml"
        }
    }
}
