pipeline {
	agent {
		label "docker"
	}
    
    stages {
		stage('verify workspace is clean') {
            steps {
                sh "docker container rm EE_AL35_OpenJDK8_UNIT -f || true"
            }
        }
        stage('run unit tests') {
            agent {
                dockerfile {
                    label 'docker'
                    dir 'ejbca/jenkins-files/EE_AL35_OpenJDK8_UNIT'
                    filename 'Dockerfile'
                    additionalBuildArgs  '--disable-content-trust=false --pull'
                    args '--group-add root'
                }
            }
            steps {
                dir ('ejbca') {
                    sh "cp /opt/conf/* conf/"
                    sh "ant -q -Dappserver.home=/tmp -Dappserver.type=jboss -Dejbca.productionmode=false clean build test:runsa"
                }
                junit "ejbca/**/reports/**/TEST-*.xml"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
