pipeline {
	agent {
		label "docker"
	}
    stages {
		stage('verify that space is clean') {
            steps {
                sh "docker container rm mariadb_softhsm -f || true"
                sh "docker container rm ee_cos7_openjdk8_wf10_softhsm_mariadb -f || true"
                sh "docker network rm bridge net_ee_cos7_openjdk8_wf10_softhsm_mariadb || true"
                sh "rm -rf ear"
            }
        }
        stage('network') {
            steps {
                sh "docker network create --driver bridge net_ee_cos7_openjdk8_wf10_softhsm_mariadb || true"
            }
        }
	stage('database') {
            steps {
                sh "docker run --name mariadb_softhsm -e MYSQL_ROOT_PASSWORD=foo123 -e MYSQL_DATABASE=ejbca -e MYSQL_USER=ejbca -e MYSQL_PASSWORD=ejbca --net=net_ee_cos7_openjdk8_wf10_softhsm_mariadb -d mariadb:10.2.17"
            }
        }
        stage('deploy and run system tests') {
            steps {
                sh "mkdir ear || true"
                dir ('ejbca/jenkins-files/EE_COS7_OpenJDK8_WF10_SOFTHSM_MariaDB') {
                    sh "docker build -t ee_cos7_openjdk8_wf10_softhsm_mariadb -m 3GB ."
                    sh "docker run --name ee_cos7_openjdk8_wf10_softhsm_mariadb --net=net_ee_cos7_openjdk8_wf10_softhsm_mariadb -v " + "$env.WORKSPACE" + ":/app ee_cos7_openjdk8_wf10_softhsm_mariadb"
                }
            }
        }
    }
    post {
        always {
            junit "ejbca/**/reports/**/TEST-*.xml"
            sh "docker stop --time=1 ee_cos7_openjdk8_wf10_nohsm_mariadb || true"
            sh "docker rm -f ee_cos7_openjdk8_wf10_nohsm_mariadb || true"
            sh "docker stop --time=1 mariadb_softhsm"
            sh "docker rm -f mariadb_softhsm"
            sh "docker network rm bridge net_ee_cos7_openjdk8_wf10_softhsm_mariadb || true"
            cleanWs()
        }
    }
}
