/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.keyrecovery;

/**
 * Home interface for KeyRecoverySession.
 */
public interface IKeyRecoverySessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/KeyRecoverySession";
   public static final String JNDI_NAME="KeyRecoverySession";

   public se.anatom.ejbca.keyrecovery.IKeyRecoverySessionRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
