package se.anatom.ejbca.keyrecovery;

/**
 * Created 2003-feb-06 22:27:07
 * Code generated by the Forte For Java EJB Workshop
 * @author tomselleck
 */

public final class KeyRecoveryDataPK implements java.io.Serializable {

    public int pK;


    public KeyRecoveryDataPK(java.math.BigInteger certificatesn, java.lang.String issuerdn) {
        this.pK =
        ((certificatesn==null?0:certificatesn.hashCode())
        ^
        (issuerdn==null?0:issuerdn.hashCode()));
    }

    public KeyRecoveryDataPK() {
    }

    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    public boolean equals(java.lang.Object otherOb) {
        if (!(otherOb instanceof se.anatom.ejbca.keyrecovery.KeyRecoveryDataPK)) {
            return false;
        }
        se.anatom.ejbca.keyrecovery.KeyRecoveryDataPK other = (se.anatom.ejbca.keyrecovery.KeyRecoveryDataPK) otherOb;
        return (pK==other.pK);
    }

    /**
     * @see java.lang.Object#hashCode()
     */
    public int hashCode() {
        return this.pK;
    }

}
