/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.keyrecovery;

/**
 * Local interface for KeyRecoveryData.
 */
public interface KeyRecoveryDataLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getIssuerDN(  ) ;

   public void setIssuerDN( java.lang.String issuerdn ) ;

   public java.lang.String getUsername(  ) ;

   /**
    * username must be called 'striped' using StringTools.strip()
    * @see se.anatom.ejbca.util.StringTools
    */
   public void setUsername( java.lang.String username ) ;

   public boolean getMarkedAsRecoverable(  ) ;

   public void setMarkedAsRecoverable( boolean markedasrecoverable ) ;

   public java.math.BigInteger getCertificateSN(  ) ;

   public void setCertificateSN( java.math.BigInteger certificatesn ) ;

   public byte[] getKeyDataAsByteArray(  ) ;

   public void setKeyDataFromByteArray( byte[] keydata ) ;

}
