#!/bin/sh

echo "exportDatabaseVariables"
echo "1 $1"
echo "2 $2"
echo "3 $3"

export DOCKERFILE_STANDALONE_DATASOURCE_JNDI_NAME="1"
export DOCKERFILE_STANDALONE_DATASOURCE_CONNECTION_URL="2"
export DOCKERFILE_STANDALONE_DATASOURCE_DRIVER="3"
export DOCKERFILE_STANDALONE_DATASOURCE_DRIVER_CLASS="4"
export DOCKERFILE_STANDALONE_DATASOURCE_USERNAME="5"
export DOCKERFILE_STANDALONE_DATASOURCE_PASSWORD="6"
export DOCKERFILE_STANDALONE_DATASOURCE_VALID_CONNECTION="7"
export DOCKERFILE_STANDALONE_DRIVER="8"