
Hypersonic
==========
CREATE TABLE HARDTOKENDATA(TOKENSN VARCHAR(256) NOT NULL,USERNAME VARCHAR(256),CTIME BIGINT NOT NULL,MTIME BIGINT NOT NULL,TOKENTYPE INTEGER NOT NULL,SIGNIFICANTISSUERDN VARCHAR(256),DATA VARBINARY,CONSTRAINT PK_HARDTOKENDATA PRIMARY KEY(TOKENSN))
CREATE TABLE HARDTOKENPROFILEDATA(ID INTEGER NOT NULL,NAME VARCHAR(256),UPDATECOUNTER INTEGER NOT NULL,DATA VARCHAR(256),CONSTRAINT PK_HARDTOKENPROFILEDATA PRIMARY KEY(ID))
CREATE TABLE HARDTOKENISSUERDATA(ID INTEGER NOT NULL,ALIAS VARCHAR(256),ADMINGROUPID INTEGER NOT NULL,DATA VARBINARY,CONSTRAINT PK_HARDTOKENISSUERDATA PRIMARY KEY(ID))
CREATE TABLE HARDTOKENCERTIFICATEMAP(CERTIFICATEFINGERPRINT VARCHAR(256) NOT NULL,TOKENSN VARCHAR(256),CONSTRAINT PK_HARDTOKENCERTIFICATEMAP PRIMARY KEY(CERTIFICATEFINGERPRINT))
CREATE TABLE HARDTOKENPROPERTYDATA(ID VARCHAR(256) NOT NULL,PROPERTY VARCHAR(256) NOT NULL,VALUE VARCHAR(256),CONSTRAINT PK_HARDTOKENPROPERTYDATA PRIMARY KEY(ID,PROPERTY))
CREATE TABLE ADMINGROUPDATA(PK INTEGER NOT NULL,ADMINGROUPNAME VARCHAR(256),CAID INTEGER NOT NULL,CONSTRAINT PK_ADMINGROUPDATA PRIMARY KEY(PK))
CREATE TABLE ADMINPREFERENCESDATA(ID VARCHAR(256) NOT NULL,DATA VARBINARY,CONSTRAINT PK_ADMINPREFERENCESDATA PRIMARY KEY(ID))
CREATE TABLE CADATA(CAID INTEGER NOT NULL,NAME VARCHAR(256),SUBJECTDN VARCHAR(256),STATUS INTEGER NOT NULL,EXPIRETIME BIGINT NOT NULL,DATA VARCHAR(256),CONSTRAINT PK_CADATA PRIMARY KEY(CAID))
CREATE TABLE AUTHORIZATIONTREEUPDATEDATA(PK INTEGER NOT NULL,AUTHORIZATIONTREEUPDATENUMBER INTEGER NOT NULL,CONSTRAINT PK_AUTHORIZATIONTREEUPDATEDATA PRIMARY KEY(PK))
CREATE TABLE ENDENTITYPROFILEDATA(ID INTEGER NOT NULL,PROFILENAME VARCHAR(256),DATA VARBINARY,CONSTRAINT PK_ENDENTITYPROFILEDATA PRIMARY KEY(ID))
CREATE TABLE CERTIFICATEPROFILEDATA(ID INTEGER NOT NULL,CERTIFICATEPROFILENAME VARCHAR(256),DATA VARBINARY,CONSTRAINT PK_CERTIFICATEPROFILEDATA PRIMARY KEY(ID))
CREATE TABLE CERTIFICATEDATA(FINGERPRINT VARCHAR(256) NOT NULL,ISSUERDN VARCHAR(256),SUBJECTDN VARCHAR(256),CAFINGERPRINT VARCHAR(256),STATUS INTEGER NOT NULL,TYPE INTEGER NOT NULL,SERIALNUMBER VARCHAR(256),EXPIREDATE BIGINT NOT NULL,REVOCATIONDATE BIGINT NOT NULL,REVOCATIONREASON INTEGER NOT NULL,BASE64CERT VARCHAR(256),USERNAME VARCHAR(256),CONSTRAINT PK_CERTIFICATEDATA PRIMARY KEY(FINGERPRINT))
CREATE TABLE CERTREQHISTORYDATA(FINGERPRINT VARCHAR(256) NOT NULL,ISSUERDN VARCHAR(256),SERIALNUMBER VARCHAR(256),TIMESTAMP BIGINT NOT NULL,USERDATAVO VARCHAR(256),USERNAME VARCHAR(256),CONSTRAINT PK_CERTREQHISTORYDATA PRIMARY KEY(FINGERPRINT))
CREATE TABLE CRLDATA(FINGERPRINT VARCHAR(256) NOT NULL,CRLNUMBER INTEGER NOT NULL,ISSUERDN VARCHAR(256),CAFINGERPRINT VARCHAR(256),THISUPDATE BIGINT NOT NULL,NEXTUPDATE BIGINT NOT NULL,BASE64CRL VARCHAR(256),CONSTRAINT PK_CRLDATA PRIMARY KEY(FINGERPRINT))
CREATE TABLE PUBLISHERDATA(ID INTEGER NOT NULL,NAME VARCHAR(256),UPDATECOUNTER INTEGER NOT NULL,DATA VARCHAR(256),CONSTRAINT PK_PUBLISHERDATA PRIMARY KEY(ID))
CREATE TABLE ADMINENTITYDATA(PK INTEGER NOT NULL,MATCHWITH INTEGER NOT NULL,MATCHTYPE INTEGER NOT NULL,MATCHVALUE VARCHAR(256),ADMINGROUPDATA_ADMINENTITIES INTEGER,CONSTRAINT PK_ADMINENTITYDATA PRIMARY KEY(PK))
CREATE TABLE LOGCONFIGURATIONDATA(ID INTEGER NOT NULL,LOGCONFIGURATION VARBINARY,LOGENTRYROWNUMBER INTEGER NOT NULL,CONSTRAINT PK_LOGCONFIGURATIONDATA PRIMARY KEY(ID))
CREATE TABLE ACCESSRULESDATA(PK INTEGER NOT NULL,ACCESSRULE VARCHAR(256),RULE INTEGER NOT NULL,ISRECURSIVE BOOLEAN NOT NULL,ADMINGROUPDATA_ACCESSRULES INTEGER,CONSTRAINT PK_ACCESSRULESDATA PRIMARY KEY(PK))
CREATE TABLE USERDATA(USERNAME VARCHAR(256) NOT NULL,SUBJECTDN VARCHAR(256),CAID INTEGER NOT NULL,SUBJECTALTNAME VARCHAR(256),SUBJECTEMAIL VARCHAR(256),STATUS INTEGER NOT NULL,TYPE INTEGER NOT NULL,CLEARPASSWORD VARCHAR(256),PASSWORDHASH VARCHAR(256),TIMECREATED BIGINT NOT NULL,TIMEMODIFIED BIGINT NOT NULL,ENDENTITYPROFILEID INTEGER NOT NULL,CERTIFICATEPROFILEID INTEGER NOT NULL,TOKENTYPE INTEGER NOT NULL,HARDTOKENISSUERID INTEGER NOT NULL,EXTENDEDINFORMATIONDATA VARBINARY,KEYSTOREPASSWORD VARCHAR(256),CONSTRAINT PK_USERDATA PRIMARY KEY(USERNAME))
CREATE TABLE KEYRECOVERYDATA(CERTSN VARCHAR(256) NOT NULL,ISSUERDN VARCHAR(256) NOT NULL,USERNAME VARCHAR(256),MARKEDASRECOVERABLE BOOLEAN NOT NULL,KEYDATA VARCHAR(256),CONSTRAINT PK_KEYRECOVERYDATA PRIMARY KEY(CERTSN,ISSUERDN))
CREATE TABLE LOGENTRYDATA(ID INTEGER NOT NULL,ADMINTYPE INTEGER NOT NULL,ADMINDATA VARCHAR(256),CAID INTEGER NOT NULL,MODULE INTEGER NOT NULL,TIME BIGINT NOT NULL,USERNAME VARCHAR(256),CERTIFICATESNR VARCHAR(256),EVENT INTEGER NOT NULL,COMMENT VARCHAR(256),CONSTRAINT PK_LOGENTRYDATA PRIMARY KEY(ID))
CREATE TABLE GLOBALCONFIGURATIONDATA(CONFIGURATIONID VARCHAR(256) NOT NULL,DATA VARBINARY,CONSTRAINT PK_GLOBALCONFIGURATIONDATA PRIMARY KEY(CONFIGURATIONID))

MySQL
=====

CREATE TABLE accessrulesdata (
    pK int(11) NOT NULL DEFAULT '0',
    accessRule varchar(250) binary NULL DEFAULT NULL,
    rule int(11) NOT NULL DEFAULT '0',
    isRecursive tinyint(4) NOT NULL DEFAULT '0',
    `AdminGroupData_accessRules` int(11) NULL DEFAULT NULL,
    PRIMARY KEY (pK)
);

CREATE TABLE adminentitydata (
    pK int(11) NOT NULL DEFAULT '0',
    matchWith int(11) NOT NULL DEFAULT '0',
    matchType int(11) NOT NULL DEFAULT '0',
    matchValue varchar(250) binary NULL DEFAULT NULL,
    `AdminGroupData_adminEntities` int(11) NULL DEFAULT NULL,
    PRIMARY KEY (pK)
);

CREATE TABLE admingroupdata (
    pK int(11) NOT NULL DEFAULT '0',
    adminGroupName varchar(250) binary NULL DEFAULT NULL,
    cAId int(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (pK)
);

CREATE TABLE adminpreferencesdata (
    id varchar(250) binary NOT NULL DEFAULT '',
    data longblob NULL DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE authorizationtreeupdatedata (
    pK int(11) NOT NULL DEFAULT '0',
    authorizationTreeUpdateNumber int(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (pK)
);

CREATE TABLE cadata (
    cAId int(11) NOT NULL DEFAULT '0',
    name varchar(250) binary NULL DEFAULT NULL,
    subjectDN varchar(250) binary NULL DEFAULT NULL,
    status int(11) NOT NULL DEFAULT '0',
    expireTime bigint(20) NOT NULL DEFAULT '0',
    data text NULL DEFAULT NULL,
    PRIMARY KEY (cAId)
);

CREATE TABLE certificatedata (
    fingerprint varchar(250) binary NOT NULL DEFAULT '',
    issuerDN varchar(250) binary NULL DEFAULT NULL,
    subjectDN varchar(250) binary NULL DEFAULT NULL,
    cAFingerprint varchar(250) binary NULL DEFAULT NULL,
    status int(11) NOT NULL DEFAULT '0',
    type int(11) NOT NULL DEFAULT '0',
    serialNumber varchar(250) binary NULL DEFAULT NULL,
    expireDate bigint(20) NOT NULL DEFAULT '0',
    revocationDate bigint(20) NOT NULL DEFAULT '0',
    revocationReason int(11) NOT NULL DEFAULT '0',
    base64Cert text NULL DEFAULT NULL,
    username varchar(250) binary NULL DEFAULT NULL,
    PRIMARY KEY (fingerprint)
);

CREATE TABLE certificateprofiledata (
    id int(11) NOT NULL DEFAULT '0',
    certificateProfileName varchar(250) binary NULL DEFAULT NULL,
    data longblob NULL DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE certreqhistorydata (
    fingerprint varchar(250) binary NOT NULL DEFAULT '',
    issuerDN varchar(250) binary NULL DEFAULT NULL,
    serialNumber varchar(250) binary NULL DEFAULT NULL,
    `timestamp` bigint(20) NOT NULL DEFAULT '0',
    userDataVO longtext NULL DEFAULT NULL,
    username varchar(250) binary NULL DEFAULT NULL,
    PRIMARY KEY (fingerprint)
);

CREATE TABLE crldata (
    fingerprint varchar(250) binary NOT NULL DEFAULT '',
    cRLNumber int(11) NOT NULL DEFAULT '0',
    issuerDN varchar(250) binary NULL DEFAULT NULL,
    cAFingerprint varchar(250) binary NULL DEFAULT NULL,
    thisUpdate bigint(20) NOT NULL DEFAULT '0',
    nextUpdate bigint(20) NOT NULL DEFAULT '0',
    base64Crl longtext NULL DEFAULT NULL,
    PRIMARY KEY (fingerprint)
);

CREATE TABLE endentityprofiledata (
    id int(11) NOT NULL DEFAULT '0',
    profileName varchar(250) binary NULL DEFAULT NULL,
    data longblob NULL DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE globalconfigurationdata (
    configurationId varchar(250) binary NOT NULL DEFAULT '',
    data longblob NULL DEFAULT NULL,
    PRIMARY KEY (configurationId)
);

CREATE TABLE hardtokencertificatemap (
    certificateFingerprint varchar(250) binary NOT NULL DEFAULT '',
    tokenSN varchar(250) binary NULL DEFAULT NULL,
    PRIMARY KEY (certificateFingerprint)
);

CREATE TABLE hardtokendata (
    tokenSN varchar(250) binary NOT NULL DEFAULT '',
    username varchar(250) binary NULL DEFAULT NULL,
    cTime bigint(20) NOT NULL DEFAULT '0',
    mTime bigint(20) NOT NULL DEFAULT '0',
    tokenType int(11) NOT NULL DEFAULT '0',
    significantIssuerDN varchar(250) binary NULL DEFAULT NULL,
    data longblob NULL DEFAULT NULL,
    PRIMARY KEY (tokenSN)
);

CREATE TABLE hardtokenissuerdata (
    id int(11) NOT NULL DEFAULT '0',
    alias varchar(250) binary NULL DEFAULT NULL,
    adminGroupId int(11) NOT NULL DEFAULT '0',
    data longblob NULL DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE hardtokenprofiledata (
    id int(11) NOT NULL DEFAULT '0',
    name varchar(250) binary NULL DEFAULT NULL,
    updateCounter int(11) NOT NULL DEFAULT '0',
    data longtext NULL DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE hardtokenpropertydata (
    id varchar(250) binary NOT NULL DEFAULT '',
    property varchar(250) binary NOT NULL DEFAULT '',
    value varchar(250) binary NULL DEFAULT NULL,
    PRIMARY KEY (id, property)
);

CREATE TABLE keyrecoverydata (
    certSN varchar(250) binary NOT NULL DEFAULT '',
    issuerDN varchar(250) binary NOT NULL DEFAULT '',
    username varchar(250) binary NULL DEFAULT NULL,
    markedAsRecoverable tinyint(4) NOT NULL DEFAULT '0',
    keyData text NULL DEFAULT NULL,
    PRIMARY KEY (certSN, issuerDN)
);

CREATE TABLE logconfigurationdata (
    id int(11) NOT NULL DEFAULT '0',
    logConfiguration longblob NULL DEFAULT NULL,
    logEntryRowNumber int(11) NOT NULL DEFAULT '0',
    PRIMARY KEY (id)
);

CREATE TABLE logentrydata (
    id int(11) NOT NULL DEFAULT '0',
    adminType int(11) NOT NULL DEFAULT '0',
    adminData varchar(250) binary NULL DEFAULT NULL,
    caId int(11) NOT NULL DEFAULT '0',
    module int(11) NOT NULL DEFAULT '0',
    `time` bigint(20) NOT NULL DEFAULT '0',
    username varchar(250) binary NULL DEFAULT NULL,
    certificateSNR varchar(250) binary NULL DEFAULT NULL,
    event int(11) NOT NULL DEFAULT '0',
    comment varchar(250) binary NULL DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE publisherdata (
    id int(11) NOT NULL DEFAULT '0',
    name varchar(250) binary NULL DEFAULT NULL,
    updateCounter int(11) NOT NULL DEFAULT '0',
    data text NULL DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE userdata (
    username varchar(250) binary NOT NULL DEFAULT '',
    subjectDN varchar(250) binary NULL DEFAULT NULL,
    cAId int(11) NOT NULL DEFAULT '0',
    subjectAltName varchar(250) binary NULL DEFAULT NULL,
    subjectEmail varchar(250) binary NULL DEFAULT NULL,
    status int(11) NOT NULL DEFAULT '0',
    type int(11) NOT NULL DEFAULT '0',
    clearPassword varchar(250) binary NULL DEFAULT NULL,
    passwordHash varchar(250) binary NULL DEFAULT NULL,
    timeCreated bigint(20) NOT NULL DEFAULT '0',
    timeModified bigint(20) NOT NULL DEFAULT '0',
    endEntityProfileId int(11) NOT NULL DEFAULT '0',
    certificateProfileId int(11) NOT NULL DEFAULT '0',
    tokenType int(11) NOT NULL DEFAULT '0',
    hardTokenIssuerId int(11) NOT NULL DEFAULT '0',
    extendedInformationData longblob NULL DEFAULT NULL,
    keyStorePassword varchar(250) binary NULL DEFAULT NULL,
    PRIMARY KEY (username)
);
