imagePullSecrets: [{ name: keyfactor-registry }]
ejbca:
  license: ejbca-license-secret
  env:
    TLS_SETUP_ENABLED: "later"
    LOG_AUDIT_TO_DB: true
    DATABASE_JDBC_URL: "jdbc:mariadb://mariadb-mariadb-galera:3306/ejbca?characterEncoding=utf8"
    DATABASE_USER: ejbcauser
  envRaw:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mariadb-passwords
          key: mariadb-password
hsm:
  enabled: true
  luna:
    enabled: true
    server_name: "192.168.30.106"
    credentials:
      certificates:
        configMap: "hsm-luna-configmap"
      privateKey:
        secret: "hsm-luna-secret-client-key2"
# needed to make softhsm volume mount to work
podSecurityContext:
  fsGroup: 10001
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional_no_ca"
    #nginx.ingress.kubernetes.io/auth-tls-secret: "default/ejbca-ingress-trust-secret"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  hosts:
    - host: "ejbca04-integrate-luna"
      paths:
        - path: /
          pathType: Prefix
