apiVersion: v1
kind: Service
metadata:
  name: test-ejbca-database-service
  labels:
    app: test-mariadb
spec:
  type: ClusterIP
  ports:
    - name: database-port
      port: 3306
      targetPort: 3306
  selector:
    app: test-mariadb
