/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.store;

/**
 * Local home interface for CertificateProfileData.
 */
public interface CertificateProfileDataLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CertificateProfileDataLocal";
   public static final String JNDI_NAME="CertificateProfileDataLocal";

   public se.anatom.ejbca.ca.store.CertificateProfileDataLocal create(java.lang.Integer id , java.lang.String certificateprofilename , se.anatom.ejbca.ca.store.certificateprofiles.CertificateProfile certificateprofile)
      throws javax.ejb.CreateException;

   public se.anatom.ejbca.ca.store.CertificateProfileDataLocal findByCertificateProfileName(java.lang.String name)
      throws javax.ejb.FinderException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public se.anatom.ejbca.ca.store.CertificateProfileDataLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
