/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.store;

/**
 * Local interface for CRLData.
 */
public interface CRLDataLocal
   extends javax.ejb.EJBLocalObject
{

   public int getCRLNumber(  ) ;

   public void setCRLNumber( int cRLNumber ) ;

   public java.lang.String getIssuerDN(  ) ;

   public java.lang.String getFingerprint(  ) ;

   public void setFingerprint( java.lang.String fingerprint ) ;

   public java.lang.String getCAFingerprint(  ) ;

   public void setCAFingerprint( java.lang.String cAFingerprint ) ;

   public long getThisUpdate(  ) ;

   /**
    * Date formated as seconds since 1970 (== Date.getTime())
    */
   public void setThisUpdate( long thisUpdate ) ;

   public long getNextUpdate(  ) ;

   /**
    * Date formated as seconds since 1970 (== Date.getTime())
    */
   public void setNextUpdate( long nextUpdate ) ;

   public java.lang.String getBase64Crl(  ) ;

   public void setBase64Crl( java.lang.String base64Crl ) ;

   public java.security.cert.X509CRL getCRL(  ) ;

   public void setCRL( java.security.cert.X509CRL incrl ) ;

   public void setIssuer( java.lang.String dn ) ;

   public void setThisUpdate( java.util.Date thisUpdate ) ;

   public void setNextUpdate( java.util.Date nextUpdate ) ;

}
