/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.store;

/**
 * Home interface for CertificateStoreSession.
 */
public interface ICertificateStoreSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CertificateStoreSession";
   public static final String JNDI_NAME="CertificateStoreSession";

   public se.anatom.ejbca.ca.store.ICertificateStoreSessionRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
