/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.store;

/**
 * Local home interface for CertificateStoreSession.
 */
public interface ICertificateStoreSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CertificateStoreSessionLocal";
   public static final String JNDI_NAME="CertificateStoreSessionLocal";

   public se.anatom.ejbca.ca.store.ICertificateStoreSessionLocal create()
      throws javax.ejb.CreateException;

}
