-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE KeyRecoveryData ADD cryptoTokenId INTEGER  NOT NULL;
-- ALTER TABLE KeyRecoveryData ADD keyAlias VARCHAR(254) DEFAULT NULL;
-- ALTER TABLE KeyRecoveryData ADD publicKeyId VARCHAR(254) DEFAULT NULL;
-- CALL SYSPROC.ADMIN_CMD('REORG TABLE KeyRecoveryData');
