-- If you are using an older version of Derby, such as 10.2, you need to drop and re-create this table. See doc/howto/create-tables-ejbca5-derby.sql for drop/create statements.
-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE KeyRecoveryData ADD cryptoTokenId INTEGER NOT NULL;
-- ALTER TABLE KeyRecoveryData ADD keyAlias VARCHAR(256) DEFAULT NULL;
-- ALTER TABLE KeyRecoveryData ADD publicKeyId VARCHAR(256) DEFAULT NULL;
