-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE KeyRecoveryData ADD cryptoTokenId INT(11) NOT NULL;
-- ALTER TABLE KeyRecoveryData ADD keyAlias VARCHAR(250) BINARY DEFAULT NULL;
-- ALTER TABLE KeyRecoveryData ADD publicKeyId VARCHAR(250) BINARY DEFAULT NULL;
