/*************************************************************************
 *                                                                       *
 *  EJBCA Community: The OpenSource Certificate Authority                *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU Lesser General Public           *
 *  License as published by the Free Software Foundation; either         *
 *  version 2.1 of the License, or any later version.                    *
 *                                                                       *
 *  See terms of license at gnu.org.                                     *
 *                                                                       *
 *************************************************************************/
package org.ejbca.ui.web.admin;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.cesecore.authentication.oauth.OAuthKeyInfo;
import org.ejbca.config.GlobalConfiguration;
import org.ejbca.ui.web.jsf.configuration.EjbcaWebBean;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;

/**
 * Bean used to display a login page.
 */
@ManagedBean
@ViewScoped
public class AdminLoginMBean extends BaseManagedBean implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(AdminLoginMBean.class);

    private EjbcaWebBean ejbcaWebBean;

    private List<Throwable> throwables = null;
    private String errorMessage;
    private Collection<OAuthKeyInfo> oauthKeys = null;

    /**
     * @return the general error which occurred
     */
    public String getError() {
        return ejbcaWebBean.getText("AUTHORIZATIONDENIED");
    }

    /**
     * @return please login message
     */
    public String getPleaseLogin() {
        return ejbcaWebBean.getText("PLEASE_LOGIN");
    }

    /**
     * @return error message generated by application exceptions
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * without access to template, we have to fetch the CSS manually
     *
     * @return path to admin web CSS file
     **/
    public String getCssFile() {
        try {
            return ejbcaWebBean.getBaseUrl() + "/" + ejbcaWebBean.getCssFile();
        } catch (Exception e) {
            // This happens when EjbcaWebBeanImpl fails to initialize.
            // That is already logged in EjbcaWebBeanImpl.getText, so log at debug level here.
            final String msg = "Caught exception when trying to get stylesheet URL, most likely EjbcaWebBean failed to initialized";
            if (log.isTraceEnabled()) {
                log.debug(msg, e);
            } else {
                log.debug(msg);
            }
            return "exception_in_getCssFile";
        }
    }

    /**
     * Invoked when login.xhtml is rendered. Show errors and possible login links.
     */
    @SuppressWarnings("unchecked")
    public void onLoginPageLoad() throws Exception {
        ejbcaWebBean = getEjbcaErrorWebBean();
        ejbcaWebBean.initialize_errorpage((HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest());
        final Map<String, Object> requestMap = FacesContext.getCurrentInstance().getExternalContext().getRequestMap();
        // Render error caught by CaExceptionHandlerFactory
        if (throwables == null) {
            throwables = (List<Throwable>) requestMap.get(CaExceptionHandlerFactory.REQUESTMAP_KEY);
            requestMap.remove(CaExceptionHandlerFactory.REQUESTMAP_KEY);
        }
        if (throwables == null) {
            log.debug("No exception thrown, could not renderer error messages.");
        } else {
            for (final Throwable throwable : throwables) {
                errorMessage = ejbcaWebBean.getText("CAUSE") + ": " + throwable.getMessage();
            }
        }

    }

    /**
     * Returns a list of OAuth Keys containing url.
     *
     * @return a list of OAuth Keys containing url
     */
    public Collection<OAuthKeyInfo> getAllOauthKeys() {
        if (oauthKeys == null) {
            oauthKeys = new ArrayList<>();
            ejbcaWebBean.reloadGlobalConfiguration();
            GlobalConfiguration globalConfiguration = ejbcaWebBean.getGlobalConfiguration();
            Collection<OAuthKeyInfo> oAuthKeyInfos = globalConfiguration.getOauthKeys().values();
            if (!oAuthKeyInfos.isEmpty()) {
                for (OAuthKeyInfo oauthKeyInfo : oAuthKeyInfos) {
                    if (!StringUtils.isEmpty(oauthKeyInfo.getUrl())) {
                        oauthKeys.add(oauthKeyInfo);
                    }
                }
            }
        }
        return oauthKeys;
    }
}
