/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.auth;

/**
 * Home interface for AuthenticationSession.
 */
public interface IAuthenticationSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AuthenticationSession";
   public static final String JNDI_NAME="AuthenticationSession";

   public se.anatom.ejbca.ca.auth.IAuthenticationSessionRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
