pipeline {
	agent {
		label "docker"
	}
    stages {
		stage('verify that space is clean') {
            steps {
                sh "docker container rm mariadb_wf14_1 -f || true"
                sh "docker container rm ee_cos7_openjdk8_wf14_nohsm_mariadb -f || true"
                sh "docker network rm bridge wf14_systest_network_1 || true"
                sh "rm -rf ear"
            }
        }
        stage('network') {
            steps {
                sh "docker network create --driver bridge wf14_systest_network_1 || true"
            }
        }
		stage('database') {
            steps {
                sh "docker run --name mariadb_wf14_1 -e MYSQL_ROOT_PASSWORD=foo123 -e MYSQL_DATABASE=ejbca -e MYSQL_USER=ejbca -e MYSQL_PASSWORD=ejbca --net=wf14_systest_network_1 -d mariadb:10.2.17"
            }
        }
        stage('deploy and run system tests') {
            steps {
                sh "mkdir ear || true"
                dir ('ejbca/jenkins-files/EE_COS7_OpenJDK8_WF14_NOHSM_MariaDB') {
                    sh "docker build -t ee_cos7_openjdk8_wf14_nohsm_mariadb -m 3GB ."
                    sh "docker run --name ee_cos7_openjdk8_wf14_nohsm_mariadb --net=wf14_systest_network_1 -v " + "$env.WORKSPACE" + ":/app ee_cos7_openjdk8_wf14_nohsm_mariadb"
                }
            }
        }
    }
    post {
        always {
            junit "ejbca/**/reports/**/TEST-*.xml"
            sh "docker stop --time=1 ee_cos7_openjdk8_wf14_nohsm_mariadb || true"
            sh "docker rm -f ee_cos7_openjdk8_wf14_nohsm_mariadb || true"
            sh "docker stop --time=1 mariadb_wf14_1"
            sh "docker rm -f mariadb_wf14_1"
            sh "docker network rm wf14_systest_network_1 || true"
            cleanWs()
        }
    }
}
