
-- AdminGroupData.pK was named "primkey" on JBoss because of an empty mapping file in EJBCA 3.x.
ALTER TABLE AdminGroupData DROP CONSTRAINT pk_admingroupdata RESTRICT;
ALTER TABLE AdminGroupData RENAME COLUMN primkey TO pK;
ALTER TABLE AdminGroupData ADD CONSTRAINT pk_admingroupdata PRIMARY KEY (pK);

-- ServiceData gets two new columns
ALTER TABLE ServiceData ADD COLUMN nextRunTimeStamp INT8 NOT NULL WITH DEFAULT;
ALTER TABLE ServiceData ADD COLUMN runTimeStamp INT8 NOT NULL WITH DEFAULT;

-- Add rowVersion column to all tables
ALTER TABLE AccessRulesData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE AdminEntityData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE AdminGroupData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE AdminPreferencesData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE ApprovalData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE AuthorizationTreeUpdateData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE CAData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE CRLData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE CertReqHistoryData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE CertificateData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE CertificateProfileData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE EndEntityProfileData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE GlobalConfigurationData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE HardTokenCertificateMap ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE HardTokenData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE HardTokenIssuerData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE HardTokenProfileData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE HardTokenPropertyData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE KeyRecoveryData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE LogConfigurationData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE LogEntryData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE ProtectedLogData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE ProtectedLogExportData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE ProtectedLogTokenData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE PublisherData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE ServiceData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE TableProtectData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE UserData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
ALTER TABLE UserDataSourceData ADD COLUMN rowVersion INT4 NOT NULL WITH DEFAULT;
