/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.log;

/**
 * Home interface for LogSession.
 */
public interface ILogSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LogSession";
   public static final String JNDI_NAME="LogSession";

   public se.anatom.ejbca.log.ILogSessionRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
