/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.log;

/**
 * Local home interface for LogEntryData.
 */
public interface LogEntryDataLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LogEntryDataLocal";
   public static final String JNDI_NAME="LogEntryDataLocal";

   public se.anatom.ejbca.log.LogEntryDataLocal create(java.lang.Integer id , int admintype , java.lang.String admindata , int caid , int module , java.util.Date time , java.lang.String username , java.lang.String certificatesnr , int event , java.lang.String comment)
      throws javax.ejb.CreateException;

   public se.anatom.ejbca.log.LogEntryDataLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
