pipeline {
	agent {
		label "docker"
	}
	environment {
	    // Use a Jenkins job name as unique identifier for related resources
        THIS_JOB_NAME = "$env.JOB_BASE_NAME"
        // This folder
        JENKINS_JOB_FOLDER = 'EE_COS7_OpenJDK8_WF10_NOHSM_DB2'
        // Folders
        BUILD_FOLDER = "${env.WORKSPACE}/${env.THIS_JOB_NAME}"
        BUILD_FOLDER_CONF = "${env.BUILD_FOLDER}/conf"
        BUILD_FOLDER_DB = "${env.BUILD_FOLDER}/database"
        // Docker container names
        DOCKER_NAME_NET  = "net_${env.THIS_JOB_NAME}"
        DOCKER_NAME_DB = "db_${env.THIS_JOB_NAME}"
        DOCKER_NAME_BASE = "ee_${env.THIS_JOB_NAME}"
        // Environment
        JDK_VERSION = '8'
        ANT_VERSION = '1.9.8'
        DB_FAMILY = 'db2'
        DB_VERSION = '11.5.0.0a'
        SERVER_FAMILY = 'wildfly'
        SERVER_VERSION = '10.1.0.Final'
	}
	stages {
		stage('Verify that space is clean') {
			steps {
				sh "docker container rm ${env.DOCKER_NAME_DB} -f || true"
				sh "docker container rm ${env.DOCKER_NAME_BASE} -f || true"
				sh "docker network rm ${env.DOCKER_NAME_NET} || true"
				sh "rm -rf ${env.BUILD_FOLDER} || true"
			}
		}
		stage('Prepare the environment') {
            steps {
                sh "echo Creating a network..."
                sh "docker network create --driver bridge ${env.DOCKER_NAME_NET} || true"
                sh "echo Creating environment setup folders..."
                sh "mkdir ${env.BUILD_FOLDER}"
                sh "mkdir ${env.BUILD_FOLDER_CONF}"
                sh "mkdir ${env.BUILD_FOLDER_DB}"

                // Copy database container
                sh "echo Copying database container..."
                sh "./ejbca/jenkins-files/common/scripts/copyDatabaseContainer.sh ${env.WORKSPACE}/ejbca/jenkins-files/common/database ${env.BUILD_FOLDER_DB} ${env.DOCKER_NAME_DB} ${env.JDK_VERSION} ${env.DB_FAMILY} ${env.DB_VERSION} ${env.SERVER_FAMILY} ${env.SERVER_VERSION}"
                sh "ls -la ${env.BUILD_FOLDER_DB}"

                // Copy server container
                sh "echo Copying application server container..."
                sh "./ejbca/jenkins-files/common/scripts/copyServerContainer.sh ${env.WORKSPACE}/ejbca/jenkins-files/common/server ${env.BUILD_FOLDER} ${env.DOCKER_NAME_DB} ${env.JDK_VERSION} ${env.DB_FAMILY} ${env.DB_VERSION} ${env.SERVER_FAMILY} ${env.SERVER_VERSION}"
                sh "ls -la ${env.BUILD_FOLDER}"
                sh "cat ${env.BUILD_FOLDER}/standalone1.xml"

                // Copy database libraries for application server
                sh "echo Copying database libraries for application server container..."

                // Copy configuration properties
                sh "echo Copying configuration properties..."
                sh "./ejbca/jenkins-files/common/scripts/copyConfigurationProperties.sh ${env.WORKSPACE}/ejbca/jenkins-files/common/conf ${env.BUILD_FOLDER_CONF} ${env.DOCKER_NAME_DB} ${env.JDK_VERSION} ${env.DB_FAMILY} ${env.DB_VERSION} ${env.SERVER_FAMILY} ${env.SERVER_VERSION}"
                sh "cat ${env.BUILD_FOLDER_CONF}/database.properties"
                sh "cat ${env.BUILD_FOLDER_CONF}/ejbca.properties"
            }
        }
		stage('Start the database container') {
			steps {
                dir ("${env.BUILD_FOLDER_DB}") {
                    sh "echo Building database container..."
                    sh "docker build -t ${env.DOCKER_NAME_DB} -m 3GB . "
                    sh "echo Building database container..."
                    // TODO Check --privileged=true -p 50000:50000
                    sh "docker run -d --name ${env.DOCKER_NAME_DB} --net=${env.DOCKER_NAME_NET} --privileged=true -p 50000:50000 -v ${env.WORKSPACE}:/database ${env.DOCKER_NAME_DB}"
                    // Sleep for database startup and warmup
                    sh "sleep 120"
                }
            }
		}
		stage('Install, deploy and run system tests') {
			steps {
			    //
			    sh "echo Building application server container..."
			    //
			    sh "echo Starting application server container..."
			}
		}
	}
	post {
		always {
			sh "docker stop --time=1 ${env.DOCKER_NAME_BASE} || true"
			sh "docker rm -f ${env.DOCKER_NAME_BASE} || true"
			sh "docker stop --time=1 ${env.DOCKER_NAME_DB} || true"
			sh "docker rm -f ${env.DOCKER_NAME_DB} || true"
			sh "docker network rm ${env.DOCKER_NAME_NET} || true"
			cleanWs()
		}
	}
}
