pipeline {
	agent {
		label "docker"
	}
    
    stages {
        stage('prune') {
            steps {
                // remove all non-running packages and images and containers
                // after pruning, all images need to be built from scratch, docker 'cache' will be empty.
                // meant to be run once per night
                // NB: this is not a jenkins SVN pipeline script, but a normal one - because we don't want 
                // pipeline to check in code for this job, we only want to  perform a quick prune.
                sh "docker system prune -f -a --volumes"
            }
        }
    }
}
