/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.authorization;

/**
 * Local interface for AccessRulesData.
 */
public interface AccessRulesDataLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getAdminGroupName(  ) ;

   public int getCaId(  ) ;

   public se.anatom.ejbca.authorization.AccessRule getAccessRuleObject(  ) ;

}
