/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.authorization;

/**
 * Primary key for AdminEntityData.
 * @todo Write migration script
 */
public class AdminEntityPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String adminGroupName;
   public int caId;
   public int matchWith;
   public int matchType;
   public java.lang.String matchValue;

   public AdminEntityPK()
   {
   }

   public AdminEntityPK( java.lang.String adminGroupName,int caId,int matchWith,int matchType,java.lang.String matchValue )
   {
      this.adminGroupName = adminGroupName;
      this.caId = caId;
      this.matchWith = matchWith;
      this.matchType = matchType;
      this.matchValue = matchValue;
   }

   public java.lang.String getAdminGroupName()
   {
      return adminGroupName;
   }
   public int getCaId()
   {
      return caId;
   }
   public int getMatchWith()
   {
      return matchWith;
   }
   public int getMatchType()
   {
      return matchType;
   }
   public java.lang.String getMatchValue()
   {
      return matchValue;
   }

   public void setAdminGroupName(java.lang.String adminGroupName)
   {
      this.adminGroupName = adminGroupName;
   }
   public void setCaId(int caId)
   {
      this.caId = caId;
   }
   public void setMatchWith(int matchWith)
   {
      this.matchWith = matchWith;
   }
   public void setMatchType(int matchType)
   {
      this.matchType = matchType;
   }
   public void setMatchValue(java.lang.String matchValue)
   {
      this.matchValue = matchValue;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.adminGroupName != null) _hashCode += this.adminGroupName.hashCode();
         _hashCode += (int)this.caId;
         _hashCode += (int)this.matchWith;
         _hashCode += (int)this.matchType;
         if (this.matchValue != null) _hashCode += this.matchValue.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof se.anatom.ejbca.authorization.AdminEntityPK) )
         return false;

      se.anatom.ejbca.authorization.AdminEntityPK pk = (se.anatom.ejbca.authorization.AdminEntityPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.adminGroupName != null )
         {
            eq = eq && this.adminGroupName.equals( pk.getAdminGroupName() );
         }
         else  // this.adminGroupName == null
         {
            eq = eq && ( pk.getAdminGroupName() == null );
         }
         eq = eq && this.caId == pk.caId;
         eq = eq && this.matchWith == pk.matchWith;
         eq = eq && this.matchType == pk.matchType;
         if( this.matchValue != null )
         {
            eq = eq && this.matchValue.equals( pk.getMatchValue() );
         }
         else  // this.matchValue == null
         {
            eq = eq && ( pk.getMatchValue() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.adminGroupName).append('.');
         toStringValue.append(this.caId).append('.');
         toStringValue.append(this.matchWith).append('.');
         toStringValue.append(this.matchType).append('.');
         toStringValue.append(this.matchValue).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
