/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.authorization;

/**
 * Local home interface for AuthorizationSession.
 */
public interface IAuthorizationSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AuthorizationSessionLocal";
   public static final String JNDI_NAME="AuthorizationSessionLocal";

   public se.anatom.ejbca.authorization.IAuthorizationSessionLocal create()
      throws javax.ejb.CreateException;

}
