-- This column is added by the JPA provider if there are sufficient privileges
-- ALTER TABLE AdminEntityData ADD tokenType VARCHAR(254) DEFAULT NULL;
-- CALL SYSPROC.ADMIN_CMD('REORG TABLE AdminEntityData');
