package se.anatom.ejbca.ca.sign;

import java.math.BigInteger;


/**
 * Interface for a serial number generator.
 *
 * @version $Id: ISernoGenerator.java,v 1.4 2003-06-26 11:43:23 anatom Exp $
 */
public interface ISernoGenerator {
    /**
     * Generates a number of serial number bytes.
     *
     * @return an array of serial number bytes.
     */
    public BigInteger getSerno();

    /**
     * Returns the number of serial number bytes generated by this generator.
     *
     * @return The number of serial number bytes generated by this generator.
     */
    public int getNoSernoBytes();

    /**
     * Sets an optional seed needed by the serno generator. This can be different things, for a
     * sequential generator it can for instance be the first number to be generated and for a
     * random generator it can be a random seed. The constructor may seed the generator enough so
     * this method may not be nessecary to call.
     *
     * @param the seed used to initilize the serno generator.
     */
    public void setSeed(long seed);
}
