package se.anatom.ejbca.ca.sign;


/** Interface for a serial number generator.
 *
 * @version $Id: ISernoGenerator.java,v 1.1 2002-08-20 12:18:23 anatom Exp $
 */
public interface ISernoGenerator {

   /** Generates a number of serial number bytes.
    *
    * @return an array of serial number bytes.
    */
    public byte[] getSerno();

   /** Returns the number of serial number bytes generated by this generator.
    *
    * @return The number of serial number bytes generated by this generator.
    */
    public int getNoSernoBytes();

}

