
package org.ejbca.core.protocol.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1.6
 * 
 */
@XmlRootElement(name = "WaitingForApprovalException", namespace = "http://ws.protocol.core.ejbca.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaitingForApprovalException", namespace = "http://ws.protocol.core.ejbca.org/", propOrder = {
    "approvalId",
    "message"
})
public class WaitingForApprovalExceptionBean {

    private int approvalId;
    private String message;

    /**
     * 
     * @return
     *     returns int
     */
    public int getApprovalId() {
        return this.approvalId;
    }

    /**
     * 
     * @param approvalId
     *     the value for the approvalId property
     */
    public void setApprovalId(int approvalId) {
        this.approvalId = approvalId;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
