/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.caadmin;

/**
 * Local home interface for CAData.
 */
public interface CADataLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CADataLocal";
   public static final String JNDI_NAME="CADataLocal";

   public se.anatom.ejbca.ca.caadmin.CADataLocal create(java.lang.String subjectdn , java.lang.String name , int status , se.anatom.ejbca.ca.caadmin.CA ca)
      throws javax.ejb.CreateException;

   public se.anatom.ejbca.ca.caadmin.CADataLocal findByName(java.lang.String name)
      throws javax.ejb.FinderException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public se.anatom.ejbca.ca.caadmin.CADataLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
