/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.ca.caadmin;

/**
 * Home interface for CAAdminSession.
 */
public interface ICAAdminSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CAAdminSession";
   public static final String JNDI_NAME="CAAdminSession";

   public se.anatom.ejbca.ca.caadmin.ICAAdminSessionRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
