/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.hardtoken;

/**
 * Local home interface for HardTokenIssuerData.
 */
public interface HardTokenIssuerDataLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HardTokenIssuerDataLocal";
   public static final String JNDI_NAME="HardTokenIssuerDataLocal";

   public se.anatom.ejbca.hardtoken.HardTokenIssuerDataLocal create(java.lang.Integer id , java.lang.String alias , int admingroupid , se.anatom.ejbca.hardtoken.HardTokenIssuer issuerdata)
      throws javax.ejb.CreateException;

   public se.anatom.ejbca.hardtoken.HardTokenIssuerDataLocal findByAlias(java.lang.String alias)
      throws javax.ejb.FinderException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public se.anatom.ejbca.hardtoken.HardTokenIssuerDataLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
