/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.hardtoken;

/**
 * Local interface for HardTokenCertificateMap.
 */
public interface HardTokenCertificateMapLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getCertificateFingerprint(  ) ;

   public java.lang.String getTokenSN(  ) ;

   public void setTokenSN( java.lang.String tokenSN ) ;

}
