/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.hardtoken;

/**
 * Local home interface for HardTokenPropertyData.
 */
public interface HardTokenPropertyLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HardTokenPropertyDataLocal";
   public static final String JNDI_NAME="HardTokenPropertyData";

   public se.anatom.ejbca.hardtoken.HardTokenPropertyLocal create(java.lang.String id , java.lang.String property , java.lang.String value)
      throws javax.ejb.CreateException;

   public se.anatom.ejbca.hardtoken.HardTokenPropertyLocal findByProperty(java.lang.String id, java.lang.String property)
      throws javax.ejb.FinderException;

   public java.util.Collection findIdsByPropertyAndValue(java.lang.String property, java.lang.String value)
      throws javax.ejb.FinderException;

   public se.anatom.ejbca.hardtoken.HardTokenPropertyLocal findByPrimaryKey(se.anatom.ejbca.hardtoken.HardTokenPropertyPK pk)
      throws javax.ejb.FinderException;

}
