/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.hardtoken;

/**
 * Local interface for HardTokenIssuerData.
 */
public interface HardTokenIssuerDataLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Integer getId(  ) ;

   public java.lang.String getAlias(  ) ;

   public void setAlias( java.lang.String alias ) ;

   public int getAdminGroupId(  ) ;

   public void setAdminGroupId( int groupid ) ;

   /**
    * Method that returns the hard token issuer data and updates it if nessesary.
    */
   public se.anatom.ejbca.hardtoken.HardTokenIssuer getHardTokenIssuer(  ) ;

   /**
    * Method that saves the hard token issuer data to database.
    */
   public void setHardTokenIssuer( se.anatom.ejbca.hardtoken.HardTokenIssuer hardtokenissuer ) ;

}
