/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.hardtoken;

/**
 * Local home interface for HardTokenCertificateMap.
 */
public interface HardTokenCertificateMapLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HardTokenCertificateMapLocal";
   public static final String JNDI_NAME="HardTokenCertificateMapLocal";

   public se.anatom.ejbca.hardtoken.HardTokenCertificateMapLocal create(java.lang.String certificateFingerprint , java.lang.String tokenSN)
      throws javax.ejb.CreateException;

   public java.util.Collection findByTokenSN(java.lang.String sn)
      throws javax.ejb.FinderException;

   public se.anatom.ejbca.hardtoken.HardTokenCertificateMapLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
