/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.hardtoken;

/**
 * Home interface for HardTokenBatchJobSession.
 */
public interface IHardTokenBatchJobSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HardTokenBatchJobSession";
   public static final String JNDI_NAME="HardTokenBatchJobSession";

   public se.anatom.ejbca.hardtoken.IHardTokenBatchJobSessionRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
