/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.hardtoken;

/**
 * Local home interface for HardTokenBatchJobSession.
 */
public interface IHardTokenBatchJobSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HardTokenBatchJobSessionLocal";
   public static final String JNDI_NAME="HardTokenBatchJobSessionLocal";

   public se.anatom.ejbca.hardtoken.IHardTokenBatchJobSessionLocal create()
      throws javax.ejb.CreateException;

}
