/*
 * Generated by XDoclet - Do not edit!
 */
package se.anatom.ejbca.hardtoken;

/**
 * Local home interface for HardTokenSession.
 */
public interface IHardTokenSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HardTokenSessionLocal";
   public static final String JNDI_NAME="HardTokenSessionLocal";

   public se.anatom.ejbca.hardtoken.IHardTokenSessionLocal create()
      throws javax.ejb.CreateException;

}
