FROM microsoft/mssql-server-linux:2017-latest

LABEL description="microsoft/mssql-server-linux"

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=MyEjbcaPass1100
ENV MSSQL_COLLATION=Latin1_General_100_CS_AS_WS_SC

EXPOSE 1433