FROM microsoft/mssql-server-linux:2017-latest

LABEL description="microsoft/mssql-server-linux"

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=MyEjbcaPass1100
ENV MSSQL_COLLATION=LATIN1_GENERAL_100_CS_AS_KS_SC_UTF8

EXPOSE 1433