pipeline {
	agent {
		label "docker"
	}
    stages {
		stage('verify that space is clean') {
            steps {
                sh "docker container rm mariadb -f || true"
                sh "docker container rm ee_ub_openjdk8_wf10_nohsm_mariadb -f || true"
                sh "rm -rf ear"
            }
        }
        stage('network') {
            steps {
                sh "docker network create --driver bridge my_isolated_bridge_network || true"
            }
        }
		stage('database') {
            steps {
                sh "docker run --name mariadb -p 3306:3306 -e MYSQL_ROOT_PASSWORD=foo123 -e MYSQL_DATABASE=ejbca -e MYSQL_USER=ejbca -e MYSQL_PASSWORD=ejbca --net=my_isolated_bridge_network -d mariadb:10.2.17"
            }
        }
        stage('deploy and run system tests') {
            steps {
                sh "mkdir ear || true"
                dir ('ejbca/jenkins-files/EE_UB_OpenJDK8_WF10_NOHSM_MariaDB') {
                    sh "docker build -t ee_ub_openjdk8_wf10_nohsm_mariadb -m 2GB ."
                    sh "docker run --name ee_ub_openjdk8_wf10_nohsm_mariadb --net=my_isolated_bridge_network -v " + "$env.WORKSPACE" + ":/app ee_ub_openjdk8_wf10_nohsm_mariadb"
                }
            }
        }
    }
    post {
        always {
            junit "ejbca/**/reports/**/TEST-*.xml"
            sh "docker stop --time=1 ee_ub_openjdk8_wf10_nohsm_mariadb"
            sh "rm -f ee_ub_openjdk8_wf10_nohsm_mariadb"
            cleanWs()
        }
    }
}
