-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE CertificateData ADD endEntityProfileId INT4 NOT NULL;
-- ALTER TABLE ApprovalData ADD approvalprofileid INT4 DEFAULT 0;
