-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE CertificateData ADD notBefore NUMBER(19);
-- ALTER TABLE CertificateData ADD endEntityProfileId NUMBER(10);
-- ALTER TABLE CertificateData ADD subjectAltName VARCHAR2(2000 byte);
--
-- Table ProfileData is new and is added by the JPA provider if there are sufficient privileges. 
-- See create-tables-database.sql
--
-- subjectDN and subjectAltName columns in UserData has been extended to accommodate longer names
-- subjectDN from 250 to 400 characters and subjectAltName from 250 to 2000 characters
-- ALTER TABLE UserData MODIFY subjectAltName VARCHAR(2000 byte);
-- ALTER TABLE UserData MODIFY subjectDN VARCHAR(400 byte);
-- ALTER TABLE CertificateData MODIFY subjectDN VARCHAR(400 byte);
