-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE CertificateData ADD endEntityProfileId INT(11);
-- ALTER TABLE ApprovalData ADD approvalprofileid INT(11) DEFAULT 0;
