-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE CertificateData ADD notBefore DECIMAL(18,0);
-- ALTER TABLE CertificateData ADD endEntityProfileId INTEGER;
-- ALTER TABLE CertificateData ADD subjectAltName LVARCHAR(2000);
