-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE CertificateData ADD notBefore BIGINT;
-- ALTER TABLE CertificateData ADD endEntityProfileId INTEGER;
-- ALTER TABLE CertificateData ADD subjectAltName VARCHAR(4000);
-- ALTER TABLE ApprovalData ADD approvalprofileid INTEGER DEFAULT 0;
