-- These columns are added by the JPA provider if there are sufficient privileges
-- ALTER TABLE CertificateData ADD endEntityProfileId NUMBER(10);
-- ALTER TABLE ApprovalData ADD approvalprofileid NUMBER(10) DEFAULT 0;
